apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fib-node
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fib-node
    app.kubernetes.io/part-of: graphtuitous
  name: fib-node
  namespace: rockbroth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fib-node
    spec:
      containers:
      - image: quay.io/jduimovich0/fib-node
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 48Mi
status: {}
